JMMClient/Forms/AboutForm.xaml
JMMClient/Forms/ImportFolder.xaml
JMMClient/Forms/RandomEpisodeForm.xaml
JMMClient/Forms/RandomSeriesForm.xaml
JMMClient/UserControls/FileRenameControl.xaml
JMMClient/UserControls/LogsControl.xaml
JMMClient/UserControls/UnrecognisedVideos.xaml

Changed links to reflect documentation, added a notice to the logs section about wait time, increased series window in unrecognized files.
I increased the series window in unrecognized files because for me it's always been really small. I don't know what the default window size JMM Desktop is so I did not increase it by much but ideally I'd like to make it bigger.

Update Website Links And Added Logs Notice

---

JMMClient/Forms/ImportFolder.xaml
JMMClient/Forms/ImportFolder.xaml.cs

As previously mentioned, removed folder selection on import folder.

Removed folder selection on Import Folder.

---

JMMClient/MainWindow.xaml
JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.resx
JMMClient/UserControls/AnimeSeries.xaml
JMMClient/UserControls/TvDBAndOtherLinks.xaml
JMMClient/UserControls/UserAdminControl.xaml.cs
JMMClient/ViewModel/AniDB_AnimeDetailedVM.cs

My proposed fixes for #56, #241 and #245.
#241 was created when I attempted to fix the bug in #232 that you were able to fix. The issue in #241 is more pressing so I rolled back the fix for #232 and commented out the code. I also made some minor changes and added a tooltip to reflect my comment in #29. 
I also changed the text for filtering at series level to what I think is more easily understandable. 
From
````Apply these filters when viewing the series for the group as well````
To
````Apply filter at series level instead of group level````

Minor Fixes

---

JMMClient/Forms/AboutForm.xaml
JMMClient/Forms/AdminMessagesForm.xaml
JMMClient/Forms/GroupFilterConditionForm.xaml
JMMClient/Forms/ImportFolder.xaml
JMMClient/MainWindow.xaml
JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.resx
JMMClient/Resources/MainListStyles.xaml
JMMClient/UserControls/FileRenameControl.xaml
JMMClient/UserControls/Settings/VideoPlayerSettingsControl.xaml

Updated all website links as well as made them easier to edit in the future by putting them in the .resx file.

Updated Links

---

JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.resx

Until I can get linking to specific tabs to work, this workaround will suffice.

Temporary fix for tab problem on site

---

JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.resx

Fixed a typo and changed some links.

Changing links.

---

JMMClient/Forms/RateSeriesForm.xaml

The rating type was overlapping the rating stars, changed the width to fix it.

Fixed overlap in rating section.

---

JMMClient/AppSettings.cs
JMMClient/UserControls/Downloads/DownloadsSearchTorrentsControl.xaml.cs

This is solution to make 99,99% Torrent client compatible.

Support for Torrent BlackHole (#267)

---

JMMClient/AppSettings.cs
JMMClient/Enums.cs
JMMClient/Forms/AboutForm.xaml
JMMClient/Forms/UpdateForm.xaml
JMMClient/JMMForWindows.csproj
JMMClient/MainWindow.xaml
JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.resx
JMMClient/UserControls/Community/CommunityLinksControl.xaml.cs
JMMClient/UserControls/Downloads/DownloadsSearchTorrentsControl.xaml.cs
JMMClient/UserControls/Downloads/DownloadsTorrentBlackHole.xaml
JMMClient/UserControls/Downloads/DownloadsTorrentBlackHole.xaml.cs
JMMClient/UserControls/Settings/AniDBMyListSettings.xaml.cs
JMMClient/ViewModel/UserSettingsVM.cs

Fix for #279, changed TvDB to Trakt.

Fix for #279, changed TvDB to Trakt.

---

JMMClient/Enums.cs

Fix for https://github.com/japanesemediamanager/jmmserver/issues/220.

Fix for AniDB MyList delete options.

---

JMMClient/AppSettings.cs
JMMClient/JMMForWindows.csproj.user
JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.resx
JMMClient/UserControls/Settings/VideoPlayerSettingsControl.xaml
JMMClient/UserControls/Settings/VideoPlayerSettingsControl.xaml.cs
JMMClient/Utilities/VideoHandler.cs
JMMClient/ViewModel/UserSettingsVM.cs

Allows users to select which of the supported players to open files with. Useful for files over http. New drop down box in Video Player tab in Settings.

Created 'Default Player' section in settings

---

JMMClient/JMMForWindows.csproj
JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.resx
JMMClient/Service References/JMMServerBinary/JMMServerBinary1.xsd
JMMClient/Service References/JMMServerBinary/JMMServerBinary2.xsd
JMMClient/Service References/JMMServerBinary/JMMServerBinary3.xsd
JMMClient/Service References/JMMServerBinary/JMMServerBinary4.xsd
JMMClient/Service References/JMMServerBinary/JMMServiceImplementation.wsdl
JMMClient/Service References/JMMServerBinary/Reference.cs
JMMClient/Service References/JMMServerBinary/Reference.svcmap
JMMClient/UserControls/UserAdminControl.xaml
JMMClient/UserControls/UserAdminControl.xaml.cs
JMMClient/ViewModel/JMMUserVM.cs

* Added support for plex users

Plex Plugin Big Update

---

JMMClient/Forms/ChangePasswordForm.xaml
JMMClient/Forms/DeleteFilesForm.xaml
JMMClient/Forms/DeleteFilesForm.xaml.cs
JMMClient/MainWindow.xaml
JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.de.resx
JMMClient/Properties/Resources.en-gb.resx
JMMClient/Properties/Resources.es.resx
JMMClient/Properties/Resources.fr.resx
JMMClient/Properties/Resources.it.resx
JMMClient/Properties/Resources.nl.resx
JMMClient/Properties/Resources.pl.resx
JMMClient/Properties/Resources.resx
JMMClient/Properties/Resources.ru.resx
JMMClient/UserControls/DashboardMetroDXControl.xaml
JMMClient/UserControls/Downloads/DownloadsTorrentBlackHole.xaml
JMMClient/UserControls/Downloads/DownloadsTorrentBlackHole.xaml.cs
JMMClient/UserControls/DuplicateFilesControl.xaml.cs
JMMClient/UserControls/EpisodeDetail.xaml.cs
JMMClient/UserControls/InfoPopup.xaml.cs
JMMClient/UserControls/MultipleFilesControl.xaml
JMMClient/UserControls/MultipleFilesDetailControl.xaml.cs
JMMClient/UserControls/Settings/AniDBMyListSettings.xaml.cs
JMMClient/UserControls/Settings/ImportSettings.xaml.cs
JMMClient/UserControls/Settings/JMMServerSettings.xaml.cs
JMMClient/UserControls/Settings/TvDBSettings.xaml.cs
JMMClient/UserControls/Settings/VideoPlayerSettingsControl.xaml.cs
JMMClient/UserControls/UnrecognisedVideos.xaml
JMMClient/UserControls/UnrecognisedVideos.xaml.cs
JMMClient/UserControls/UserAdminControl.xaml

- Added Folder Browser for Torrent Black Hole
- More hardcoded language strings localized
Please wait to merge until I can do a final sweep for hardcoded language strings.

Additional 3.5 Work

---

JMMClient/Forms/NewSeries.xaml
JMMClient/MainWindow.xaml
JMMClient/UserControls/DashboardControl.xaml
JMMClient/UserControls/DashboardMetroDXControl.xaml
JMMClient/UserControls/Downloads/DownloadSettingsAnimeBytes.xaml
JMMClient/UserControls/Downloads/DownloadSettingsBakaBT.xaml
JMMClient/UserControls/Downloads/DownloadsBrowseTorrentsControl.xaml
JMMClient/UserControls/Downloads/DownloadsSearchTorrentsControl.xaml
JMMClient/UserControls/Downloads/DownloadsTorrentMonitorControl.xaml
JMMClient/UserControls/EpisodeDetail.xaml
JMMClient/UserControls/GroupFilterAdmin.xaml
JMMClient/UserControls/MultipleFilesControl.xaml
JMMClient/UserControls/MultipleFilesDetailControl.xaml
JMMClient/UserControls/Settings/AniDBDownloadSettings.xaml
JMMClient/UserControls/Settings/AniDBMyListSettings.xaml
JMMClient/UserControls/Settings/DisplayImageSizesSettings.xaml
JMMClient/UserControls/Settings/DisplayStyleSettings.xaml
JMMClient/UserControls/Settings/ImportSettings.xaml
JMMClient/UserControls/Settings/LanguagePreferenceSettings.xaml
JMMClient/UserControls/Settings/MALSettings.xaml
JMMClient/UserControls/Settings/MovieDBSettings.xaml
JMMClient/UserControls/Settings/TvDBSettings.xaml
JMMClient/UserControls/Settings/WebCacheBasicSettings.xaml
JMMClient/UserControls/TvDBAndOtherLinks.xaml

Fixed some typos and localized a few strings.
Fixed tooltip localization although it takes effect only after a restart.

Localization fixes.

---

JMMClient/Forms/GroupFilterConditionForm.xaml.cs
JMMClient/Forms/NewSeries.xaml.cs
JMMClient/MainWindow.xaml.cs
JMMClient/UserControls/UnrecognisedVideos.xaml.cs
JMMClient/ViewModel/MainListHelperVM.cs

Unlike https://github.com/japanesemediamanager/jmmclient/pull/367, this PR actually has the changes from https://github.com/japanesemediamanager/jmmclient/pull/362.

Baine's PR fixes.

---

JMMClient/Downloads/TorrentLink.cs
JMMClient/Downloads/TorrentsAnimeBytes.cs
JMMClient/Downloads/TorrentsBakaBT.cs
JMMClient/Downloads/TorrentsNyaa.cs
JMMClient/Downloads/TorrentsSukebei.cs
JMMClient/Forms/SelectTvDBEpisodeForm.xaml
JMMClient/MainWindow.xaml.cs
JMMClient/UserControls/AnimeGroupControl.xaml
JMMClient/UserControls/AnimeGroupControl.xaml.cs
JMMClient/UserControls/AnimeSeriesSimplifiedControl.xaml
JMMClient/UserControls/Downloads/DownloadsBrowseTorrentsControl.xaml
JMMClient/UserControls/Downloads/DownloadsSearchTorrentsControl.xaml
JMMClient/UserControls/EpisodeDetail.xaml
JMMClient/UserControls/EpisodeDetail.xaml.cs
JMMClient/UserControls/EpisodeList.xaml
JMMClient/UserControls/EpisodeList.xaml.cs
JMMClient/UserControls/IgnoredFiles.xaml
JMMClient/UserControls/IgnoredFiles.xaml.cs
JMMClient/UserControls/UnrecognisedVideos.xaml.cs
JMMClient/ViewModel/MainListHelperVM.cs
JMMClient/ViewModel/PlaylistVM.cs

(My first pull request so sorry if I did something wrong, picked some backlog for my first one)
Had a look into 
https://github.com/japanesemediamanager/jmmclient/issues/31
Hope its okay what I did, not sure if its okay that I simply called the BeginInvoke instead of using some backgroundworker to do the job, and I kinda missused the 
MainListHelperVM.Instance.LastGroupForGF for an AnimeSeriesVM instead of a group but I believe thats okay since in the collection view there is a mixture between AnimeGroupVMs and AnimeSeriesVMs and the method
_HighlightMainListItem_
only highlighted the last selected AnimeGroupVM with the existing code.

Fix for issues #31, #40, #61, #124, #263, #291, #331, #355

---

JMMClient/Forms/SearchMALForm.xaml
JMMClient/Forms/SearchMovieDBForm.xaml
JMMClient/Forms/SearchTraktForm.xaml
JMMClient/Forms/SearchTvDBForm.xaml
JMMClient/Forms/SelectAniDBTitleForm.xaml

BindingExpression path error 'ObjectType' property not found on 'object'

Fix for System.Windows.Data Error: 40

---

JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.de.resx
JMMClient/Properties/Resources.en-gb.resx
JMMClient/Properties/Resources.es.resx
JMMClient/Properties/Resources.fr.resx
JMMClient/Properties/Resources.it.resx
JMMClient/Properties/Resources.nl.resx
JMMClient/Properties/Resources.pl.resx
JMMClient/Properties/Resources.pt.resx
JMMClient/Properties/Resources.resx
JMMClient/Properties/Resources.ru.resx
JMMClient/Service References/JMMServerBinary/JMMServerBinary.wsdl
JMMClient/Service References/JMMServerBinary/JMMServerBinary1.xsd
JMMClient/Service References/JMMServerBinary/JMMServerBinary2.xsd
JMMClient/Service References/JMMServerBinary/JMMServerBinary3.xsd
JMMClient/Service References/JMMServerBinary/JMMServiceImplementation.wsdl
JMMClient/Service References/JMMServerBinary/Reference.cs
JMMClient/ViewModel/JMMServerVM.cs

Buttons will work with non-english locale as they use status codes now. Closes #382.

Use structure for queue status instead of strings.

---

JMMClient/MainWindow.xaml.cs
JMMClient/ViewModel/AnimeSeriesVM.cs

Fix TvDBSeriesV2 list not cleared.
Fix AnimeSeriesSimplifiedControl being instantiated twice.
Helps with #387

Small fixes for #387

---

JMMClient/ViewModel/MainListHelperVM.cs

Remove delegate

---

JMMClient/Forms/RandomEpisodeForm.xaml.cs

Replace with foreach, same as in random series

---

JMMClient.sln
JMMClient/MainWindow.xaml.cs

Prevent duplicate filter

---

JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.de.resx
JMMClient/Properties/Resources.en-gb.resx
JMMClient/Properties/Resources.es.resx
JMMClient/Properties/Resources.fr.resx
JMMClient/Properties/Resources.it.resx
JMMClient/Properties/Resources.nl.resx
JMMClient/Properties/Resources.pl.resx
JMMClient/Properties/Resources.pt.resx
JMMClient/Properties/Resources.resx
JMMClient/Properties/Resources.ru.resx
JMMClient/ViewModel/JMMServerVM.cs

Needed for server issue https://github.com/japanesemediamanager/jmmserver/issues/321

New server status for LinkAniDBTvDB

---

JMMClient/UserControls/AnimeSeries.xaml
JMMClient/UserControls/AnimeSeries.xaml.cs
JMMClient/UserControls/RelatedAnimeControl.xaml
JMMClient/UserControls/RelatedAnimeControl.xaml.cs
JMMClient/UserControls/SimilarAnimeControl.xaml
JMMClient/UserControls/SimilarAnimeControl.xaml.cs

Hide buttons if there is not data to show

---

JMMClient/UserControls/RelatedAnimeControl.xaml.cs
JMMClient/UserControls/SimilarAnimeControl.xaml.cs

Restore code removed accidentally by #423

Restore accidentally removed code

---

JMMClient/Forms/MoveSeries.xaml
JMMClient/Forms/MoveSeries.xaml.cs
JMMClient/ViewModel/AnimeGroupVM.cs

Fixes error in New group, and Move series

---

JMMClient/MainWindow.xaml.cs
JMMClient/UserControls/GroupFilterAdmin.xaml
JMMClient/ViewModel/GroupFilterVM.cs

Fixes server issue https://github.com/japanesemediamanager/jmmserver/issues/318

Fixing filters created as locked

---

JMMClient/AppSettings.cs
JMMClient/UserControls/Settings/VideoPlayerSettingsControl.xaml
JMMClient/UserControls/Settings/VideoPlayerSettingsControl.xaml.cs
JMMClient/VideoPlayers/ZoomPlayerVideoPlayer.cs
JMMClient/ViewModel/UserSettingsVM.cs

Added auto-detecting for all zoom player settings, no setup required other than enabling TCP control server in the player itself for playback tracking.
Corrected video player settings alignments.

Zoom Player setup enhancements.

---

JMMClient/Properties/Resources.Designer.cs
JMMClient/Properties/Resources.de.resx
JMMClient/Properties/Resources.en-gb.resx
JMMClient/Properties/Resources.es.resx
JMMClient/Properties/Resources.fr.resx
JMMClient/Properties/Resources.it.resx
JMMClient/Properties/Resources.nl.resx
JMMClient/Properties/Resources.pl.resx
JMMClient/Properties/Resources.pt.resx
JMMClient/Properties/Resources.resx
JMMClient/Properties/Resources.ru.resx
JMMClient/ViewModel/JMMServerVM.cs

Add missing queue states for the ones added in https://github.com/japanesemediamanager/ShokoServer/commit/26cc7280631c72388954efbc99feedd637d548de
https://github.com/japanesemediamanager/ShokoServer/commit/a0730d6a0286c2ca57027a112a692661ab64144e

Add missing queue states

---

Shoko.Desktop/Forms/SearchTraktForm.xaml.cs

Any idea why webcache started returning null here?

Trakt linking fix

---

Shoko.Desktop/MainWindow.xaml.cs
Shoko.Desktop/UserControls/BookmarksControl.xaml
Shoko.Desktop/ViewModel/VM_UserSettings.cs
Shoko.Desktop/WPFHelpers/ScrollWheelHelper.cs

Fix https://github.com/ShokoAnime/ShokoDesktop/issues/576 and https://github.com/ShokoAnime/ShokoDesktop/issues/560

[F] Fix blank group when cancelling edit and fix bookmarks gui

---

.github/workflows/daily.yml

The build workflow fails at this step, this should fix it.

ci: update deprecated actions/upload-artifact
